### ISSUE TITLE
Tiled panes

### ISSUE THREAD

**Issue by abitrolly** [epiclabs-io/winman#1]
I am looking for some framework that allows to replicate the interface of https://www.farmanager.com/screenshots.php?l=en Wonder if `winman` can do this.

Note that there is no extra controls for mouse as the interface is supposed to encourage people to use keyboard.

**Comment by jpeletier** [comment]
Yes, you should be able to replicate this with Winman. Mouse is optional. You would have to implement shortcuts to switch windows, etc, but  all is there for you to build an application like farmanager. Items like buttons, panes, etc, are standard `tview` widgets

**Comment by abitrolly** [comment]
Do I have to track window overlaps and constrain resizes myself? Or Winman does can do this automatically like a tiled wm?

**Comment by jpeletier** [comment]
Winman will help you more for this type of situation :![](https://www.farmanager.com/img/screen/colors.png) where different windows can be on top of each other. 

If you want to force windows to not overlap, you can combine it with the Flex widget of tview, which deals with non-overlapping panes. For example, the file list in the background of the above picture could be a Flex widget inside a Winman window that is in the background.
